### ISSUE TITLE
Can i use this for wordpress plugin development

### ISSUE THREAD

**Issue by hamedmoody** [jgrossi/corcel#101]
hi
your package is great.
but can i write a wordpress plugin and use Corcel in my plugin?
Thanks

**Comment by jgrossi** [comment]
Hi @hamedmoody! You can but I don't suggest that. It's better for you to use composer inside your Wordpress project. For example, you can put all WP files in `public` folder and in the project root you install composer. 

So you will have something like `vendor` folder and `public` folder (with WP files). So inside your `functions.php` (theme file) you include the `vendor/autoload.php` file and so you can use any composer package inside your WP environment. Just add `jgrossi/corcel` in composer and call the classes you want ;-)

This is better because you can use other libraries (not only Corcel) inside Wordpress and make your project more secure and with a lot of functionalities you can find as composer package.

Any question just ask.

**Comment by jgrossi** [comment]
You can create a Wordpress plugin that only include `vendor/autoload.php` file. This will be your plugin ;-)

The main goal of Corcel is to allow you to use a custom framework with Wordpress, using for example, Slim Framework, Silex, Symfony, Zend, Laravel, **other framework here**, and just get WP data from database.

But you can use it the way you want :D
