### ISSUE TITLE
Performance issue 

### ISSUE THREAD

**Issue by webwizo** [jgrossi/corcel#166]
Hi,

I am working on Laravel Project with WordPress, did you ever try if WordPress has large amount of data like 50,000 Posts? I am experiencing it and Laravel is way too slow than WordPress for getting data.

Any solution?

**Comment by QWp6t** [comment]
It's most likely how you've structured your logic, not the fault of WordPress or Laravel, per se.

Your queries should be executed outside of loops, for example. That's probably the biggest mistake that people make. You can use a loop to prepare your query, but execute it outside of the loop so that it's all done as one query, instead of multiple queries for each loop iteration. If you're using ACF, that will also thrash your database.

At any rate, you're probably not going to get any solutions when you've provided no code.

**Comment by webwizo** [comment]
I just used a simple query 
`Post::wherePostName('slug_here')->first();`

But still getting result very slow, and I am not using any kind of loop.

**Comment by jgrossi** [comment]
Hi @webwizo thanks for the message. How many SQL queries this line of code is generating? Thanks

**Comment by josec89** [comment]
If you are using laravel, use this plugin:

https://github.com/barryvdh/laravel-debugbar

**Comment by webwizo** [comment]
@josec89 I am already using it. I just wanted to know that Laravel Relations can handle large amount of data as Corcel are using?

**Comment by jgrossi** [comment]
@webwizo Corcel makes less SQL queries that a default WP installation. How many queries you have? Maybe you should use `with()` Eloquent method to decrease these queries. Tell us how many queries are you having please. Best.

**Comment by josec89** [comment]
Well, In my opinion the Wordpress tables are quite messed up, but it should work well even so. If you are getting the posts by slug, you should add an index to that field in the database, otherwise you could add the id after the slug in the urls, something like:

```
the-title-of-my-post-5105
```

That way you could search directly by ID.

Another must-have thing is **cache** -- You should only make a DB call once in a while (15 minutes cache, or something more sophisticated like cache until the post changed)

Hope, this helped

**Comment by webwizo** [comment]
Normally, I just need PostMeta with every Posts, so I have used with() with query. But I have some live urls in PostContent column, is there any chance that you are executing those urls from PostContent?

**Comment by webwizo** [comment]
@josec89 that's a great idea if I use ID/slug so that I can use query with ID and thats already index by default, i guess and off course second option is cache, I can use it.

@jgrossi I have data from 2011 till present, and almost 50,000 rows...

**Comment by josec89** [comment]
The cache thing should be a must-do, and it's really easy in Laravel projects! :)

**Comment by jgrossi** [comment]
@webwizo I have a project running Corcel with more than 500,000 posts and no performance problems. Using a simple find method, or where, you should get 1 or 2 queries, and you said you're not inside a loop so your command `Post::wherePostName('slug_here')->first();` is not the problem, even the 50,000 rows. Like @josec89 said, you should cache this using Laravel (with Redis, for example) or another way, you have many.

What I'd like to know is, when you use `Post::wherePostName('slug_here')->first();` how many queries do you have using this specific code block? It's not about how many rows you have, but how many queries your app is making with this single line of code.

Best regards :)

**Comment by webwizo** [comment]
![2016-05-30_17-39-05](https://cloud.githubusercontent.com/assets/1593953/15649806/b16bd364-268d-11e6-8cb0-c341ecaf42c0.jpg)

Please check Debugbar summary for queries.

**Comment by jgrossi** [comment]
@webwizo you're having 3 queries for now. If you use the `dev` branch you'll have just 2 :) I'm gonna release `v1.0.11` now and you should only update your composer to get these last changes. I strongly suggest you to use a cache layer, because this is not a Corcel or WordPress or Laravel problem. With 50,000+ rows it's time to think about that :) Cheers!

**Comment by webwizo** [comment]
That's why I was confused why it is happening, while everything is right. Well, thank you for your clearance. I am trying to do it on fresh Laravel project so that I can find the issue.

Thank you once again.

**Comment by jgrossi** [comment]
@webwizo any question just ask :) welcome again!
