### ISSUE TITLE
Could not use wordpress functions in model

### ISSUE THREAD

**Issue by duyngha** [jgrossi/corcel#179]
Does anyone know why I could not use wordpress functions in class which extends from corcel such as model.

**Comment by rundef** [comment]
Hi, do you have a code example that's not working ?

**Comment by jgrossi** [comment]
Hey @duyngha are you trying to use WordPress functions inside classes? Corcel does not include `wp-load.php` file, so you will not have WP functions using it. Corcel makes the work of getting data from the database easier, for WP environments. If you need to use WP functions like `get_posts` or even `wp_nav_menu`, etc, you have to include `/where/your/wordpress/is/wp-load.php` file. 

Let's suppose you have a bootstrap file like `/bootstrap.php` and there you're including Composer autoload. You can include WP there too, and you can use WP functions. Just pay attention to the overloading, because you are including so much PHP files, ok?

```
// My bootstrap file
require __DIR__.'/vendor/autoload.php';
require __DIR__.'/public/wordpress/wp-load.php';
$posts = get_posts(array());
```

Any questions just ask. Best regards.

**Comment by duyngha** [comment]
@jgrossi Thank you very much.

**Comment by jgrossi** [comment]
You're welcome!
