### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by davidsoderberg** [jgrossi/corcel#20]
Hi, Great work with adding eloquent to Wordpress :smile: 
This should be integrated in to Themosis, maybe do a pull request to them?

**Comment by jgrossi** [comment]
Hi David!

First thanks for the message. I took a look on Themosis and that's a great
job too.

About Corcel and Themosis how Corcel would be integrated inside Themosis?

Thanks a lot. Cheers.

Junior GROSSI
*www.grossi.io <http://www.grossi.io>*

**Comment by davidsoderberg** [comment]
Yes, Themosis are not using Eloquent yet so that part could Corcel solve.
Themosis is wordpress with Laravel integrated to it so you can use Laravel inside of Wordpress themes/plugins.

**Comment by jgrossi** [comment]
Sure man, you can integrate them together. I have some features I have to implement inside Corcel but time is running over hehe.
If you to include Corcel inside Themosis be welcome ;-) It's nice because the Corcel will have new contributors too and they can walk together.
I've used Corcel with pure PHP or even Silex, for example, so it's nice to be used for more and more people.
Thanks!

**Comment by davidsoderberg** [comment]
I am not at all owner of themosis but I hope the owner of that project accept a pull requst from you. That would be useful for me using themosis.

**Comment by jgrossi** [comment]
Yep! I'm gonna try an issue on the themosis repo! Thanks

**Comment by davidsoderberg** [comment]
NP
