### ISSUE TITLE
No clear instructions, will wordpress run standalone or in the same directory as Laravel?

### ISSUE THREAD

**Issue by andreasbakir** [jgrossi/corcel#370]
First of all great job on this package! I really like the WP backend and I love programming Laravel Apps. I only have one question where should I install wordpress? I would like to do something like this: http://laravelproject.com/wp-admin but the way I understand this package works is that Laravel runs on itself and wordpress as well. So that would mean that the frontend would be visible on http://laravelproject.com and to access the backend I need to visit http://wordpressproject.com/wp-admin. 

Maybe I am wrong and they aren't separated, but the docs don't help me out when it comes to configuring wordpress.

To make my self clear in short: I would like to go http://mylaravelproject.com/wp-admin to access the wordpress backend, is this possible? If so how?

**Comment by jgrossi** [comment]
Hi @andreasbakir thanks for the message. Actually Corcel works with the WP database. It doesn't matter if your WordPress installation is in server X and Laravel one server Y, they can be in different places, servers, countries, etc. The only thing you need to make sure Corcel will be working is creating a Laravel database connection pointing to the WP database and let Corcel knows.

On my blog there's another approach to join both WP and Laravel, which requires both in the same virtual hosts (or just servers), because you have to include files, etc, but using Corcel you only need to know where WP database is. The blog I said: http://blog.jgrossi.com/2014/working-with-laravel-4-and-wordpress-together/

**Comment by andreasbakir** [comment]
hi @jgrossi thanks for the fast answer! Aah okay.. I understand, the problem I am having with this is that the wordpress backend is going to be on another domain, it would have been nice if you could access the wp-admin (wp cms backend) from within the laravel application something like, mylaravelproject.com/wp-admin or /backend or something else. 

Anyway thank you for your reply!

**Comment by jgrossi** [comment]
@andreasbakir you can do that creating a route in Laravel redirecting to the WP admin panel login page for example. You can even use NGINX to keep the URL the Laravel one but showing the WP admin page :-)
