### ISSUE TITLE
question: Are there any benefits using corcel instead of wp-api?

### ISSUE THREAD

**Issue by dejanmilosevic0** [jgrossi/corcel#395]
corcel will be running via laravel and wp-api via wordpress that is clear, but question is more about benefits of querying and database handle, does corcel have benefits or drawbacks with geting data from wordpress against wp-api? Question is not regarding fact that wi will need to implement our own rest endpoints when using corcel, it is more about is performance and comptability.

**Comment by danieluyo** [comment]
I see corcel one way for scale a Wordpress website. Its more easier scale the app where consume assets and DB only.

**Comment by codeserk** [comment]
This packages reads the database instead of asking wordpress for its info. That has some benefits but also some drawbacks:

## The good
Having access to database makes things faster and easier, you can build Eloquent queries with complex relationships and stuff like that

## The bad
Wordpress offers a layer above its database, it processes some data and you lose that when you access directly to the database, so `wp-api` offers that kind of information.

I would use this package for most part of your project (getting posts, meta, users ...) and consider `wp-api` when reading from database is not enough, and you need to call specific endpoints, or achieve something this package is unable :)

Hope it helped :)

**Comment by jgrossi** [comment]
@danieluyo I think @josec89 answer was really good 😎the big advantage of Corcel is that you can customize the data you get from the database, like it is stored. any question just ask.

**Comment by aftabnaveed** [comment]
Many wordpress features come through its plugins, how does Corcel handle those?

**Comment by interludic** [comment]
@jgrossi Perhaps corcel could consume some endpoints from wp rest api, and convert to elouqent?

collect(endpoint/);

**Comment by jgrossi** [comment]
@aftabnaveed thanks for the question! Actually, Corcel works at the database level, so if the plugin changes data and save them to the database, Corcel can get it easily. Some other plugins in other hand change the data after fetching them in the database, so Corcel is not able to do that, only if we develop a plugin that does the same logic, like `corcel/acf` does.

**Comment by jgrossi** [comment]
@interludic Corcel works at the database level only, not HTTP requests. The main goal of Corcel is allowing developers to have total control about the data, directly in the database.

**Comment by vlahde** [comment]
Hi, I am using Wordpress with plugin called Elementor, which alters data after it is fetched from the database. I understand that Corcel is not necessarily made for this but is there any workaround to make Elementor plugin work under Corcel?
