### ISSUE TITLE
Unserialize meta value from post

### ISSUE THREAD

**Issue by emanuellopes** [jgrossi/corcel#503]
- Corcel Version: 3.0.0
- Framework Name & Version: WordPress 5.3.2
- PHP Version: 7.3
- Database Driver & Version: mariaDB

### Description:
I'm trying convert a post to Json but I can't. Always receive this error.

Notice: unserialize(): Error at offset 0 of 1 bytes in /var/www/html/wp-content/themes/blog/vendor/jgrossi/corcel/src/Model/Meta/Meta.php on line 38 Notice: unserialize(): Error at offset 0 of 12 bytes in /var/www/html/wp-content/themes/blog/vendor/jgrossi/corcel/src/Model/Meta/Meta.php on line 38

I checked the Meta.php file a found out the problem, 
You are using this function  
$value = unserialize($this->meta_value);

But I'm think you must avoid this function because can be exploited, can repalce that by json_decode or json_encode.

### Steps To Reproduce:
1 - Create a custom field and add a number on field, for example 1
2 - try find a post

$post = Post::find( 1 )->toJson();

**Comment by jgrossi** [comment]
hey @emanuellopes. I think in this case we are just trying to reproduce WP's behavior, so the `unserialize()` call is required because it's how it works basically. I'd suggest you to create your own `Post` class extending Corcel's one then overriding the method you want to, avoid any other problem you have to deal with later. thank you

**Comment by emanuellopes** [comment]
Thanks @jgrossi
